# Generated by Django 5.2.3 on 2025-12-30 09:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('c_id', models.AutoField(primary_key=True, serialize=False)),
                ('chapter_no', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['subject', 'chapter_no'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('s_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper_type', models.CharField(choices=[('Theory', 'Theory'), ('Descriptive', 'Descriptive'), ('Objective', 'Objective')], max_length=50)),
                ('question', models.TextField()),
                ('key1', models.CharField(blank=True, max_length=255, null=True)),
                ('key2', models.CharField(blank=True, max_length=255, null=True)),
                ('key3', models.CharField(blank=True, max_length=255, null=True)),
                ('key4', models.CharField(blank=True, max_length=255, null=True)),
                ('correct_text', models.CharField(blank=True, max_length=255, null=True)),
                ('explanation', models.TextField(blank=True)),
                ('report', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='home.chapter')),
            ],
        ),
        migrations.AddField(
            model_name='chapter',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='home.subject'),
        ),
        migrations.CreateModel(
            name='UserChapterStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_questions', models.PositiveIntegerField(default=0)),
                ('attempted', models.PositiveIntegerField(default=0)),
                ('correct', models.PositiveIntegerField(default=0)),
                ('wrong', models.PositiveIntegerField(default=0)),
                ('score_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('last_attempt', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_stats', to='home.chapter')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapter_stats', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserQuestionAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_text', models.CharField(blank=True, max_length=255, null=True)),
                ('is_correct', models.BooleanField()),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_attempts', to='home.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_attempts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['chapter', 'paper_type'], name='home_questi_chapter_ffb367_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='chapter',
            unique_together={('subject', 'chapter_no')},
        ),
        migrations.AddIndex(
            model_name='userchapterstats',
            index=models.Index(fields=['user', 'chapter'], name='home_userch_user_id_6f053d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userchapterstats',
            unique_together={('user', 'chapter')},
        ),
        migrations.AddIndex(
            model_name='userquestionattempt',
            index=models.Index(fields=['user', 'question'], name='home_userqu_user_id_cea5d0_idx'),
        ),
        migrations.AddIndex(
            model_name='userquestionattempt',
            index=models.Index(fields=['user', 'is_correct'], name='home_userqu_user_id_2d0589_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userquestionattempt',
            unique_together={('user', 'question')},
        ),
    ]
