# Generated by Django 5.2.3 on 2025-12-30 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_chapter_subject_question_chapter_subject_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='id',
        ),
        migrations.RemoveField(
            model_name='userchapterstats',
            name='id',
        ),
        migrations.RemoveField(
            model_name='userquestionattempt',
            name='id',
        ),
        migrations.AddField(
            model_name='question',
            name='q_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='userchapterstats',
            name='uc_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='userquestionattempt',
            name='uq_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
