# Generated by Django 5.2.3 on 2025-12-30 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_question_id_remove_userchapterstats_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='paper_type',
            field=models.CharField(choices=[('MCQ', 'MCQ'), ('Book Line MCQ', 'Book Line MCQ'), ('Past Paper MCQ', 'Past Paper MCQ')], max_length=50),
        ),
    ]
