# Generated by Django 5.2.3 on 2025-12-31 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_question_paper_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PastPaperSubject',
            fields=[
                ('ps_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('p_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PastPaper',
            fields=[
                ('pp_id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.PositiveIntegerField()),
                ('pdf_file', models.FileField(upload_to='past_papers/%Y/%m/%d/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='past_papers', to='home.pastpapersubject')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='past_papers', to='home.province')),
            ],
            options={
                'ordering': ['-year', 'province', 'subject'],
                'unique_together': {('province', 'subject', 'year')},
            },
        ),
    ]
