# Generated by Django 5.2.3 on 2025-12-31 10:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_pastpapersubject_province_pastpaper'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='province',
            options={},
        ),
        migrations.CreateModel(
            name='PastPaperYear',
            fields=[
                ('ppy_id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.PositiveIntegerField()),
                ('slug', models.SlugField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='years', to='home.province')),
            ],
            options={
                'ordering': ['province', '-year'],
                'unique_together': {('province', 'year')},
            },
        ),
        migrations.CreateModel(
            name='PastPaperQuestion',
            fields=[
                ('ppq_id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('key1', models.CharField(blank=True, max_length=255, null=True)),
                ('key2', models.CharField(blank=True, max_length=255, null=True)),
                ('key3', models.CharField(blank=True, max_length=255, null=True)),
                ('key4', models.CharField(blank=True, max_length=255, null=True)),
                ('correct_text', models.CharField(blank=True, max_length=255, null=True)),
                ('explanation', models.TextField(blank=True)),
                ('report', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='home.pastpaperyear')),
            ],
        ),
        migrations.CreateModel(
            name='UserPastPaperAttempt',
            fields=[
                ('uppa_id', models.AutoField(primary_key=True, serialize=False)),
                ('selected_text', models.CharField(blank=True, max_length=255, null=True)),
                ('is_correct', models.BooleanField()),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_attempts', to='home.pastpaperquestion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='past_paper_attempts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='PastPaper',
        ),
        migrations.DeleteModel(
            name='PastPaperSubject',
        ),
        migrations.AddIndex(
            model_name='pastpaperquestion',
            index=models.Index(fields=['year'], name='home_pastpa_year_id_c8bf84_idx'),
        ),
        migrations.AddIndex(
            model_name='userpastpaperattempt',
            index=models.Index(fields=['user', 'question'], name='home_userpa_user_id_5f8eeb_idx'),
        ),
        migrations.AddIndex(
            model_name='userpastpaperattempt',
            index=models.Index(fields=['user', 'is_correct'], name='home_userpa_user_id_6d5ae8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userpastpaperattempt',
            unique_together={('user', 'question')},
        ),
    ]
