# Generated by Django 5.2.3 on 2026-01-02 12:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_province_options_pastpaperyear_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionReport',
            fields=[
                ('r_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField(help_text='Description of the issue with this question')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved', models.BooleanField(default=False)),
                ('past_paper_question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='home.pastpaperquestion')),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='home.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'created_at'], name='home_questi_user_id_25c9e9_idx'), models.Index(fields=['question'], name='home_questi_questio_0d2284_idx'), models.Index(fields=['past_paper_question'], name='home_questi_past_pa_fb6651_idx')],
            },
        ),
    ]
