# Generated by Django 5.2.3 on 2026-01-04 03:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_questionreport'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralCode',
            fields=[
                ('ref_id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(help_text='Unique referral/coupon code', max_length=50, unique=True)),
                ('commission_percentage', models.DecimalField(decimal_places=2, default=5.0, help_text='Commission percentage for the referrer', max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('total_uses', models.PositiveIntegerField(default=0, help_text='Total number of times this code has been used')),
                ('total_commission_earned', models.DecimalField(decimal_places=2, default=0.0, help_text='Total commission earned from this code', max_digits=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_codes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('p_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Payment amount', max_digits=10)),
                ('transaction_id', models.CharField(blank=True, help_text='Transaction ID or reference number', max_length=100, null=True)),
                ('payment_method', models.CharField(blank=True, help_text='Payment method (e.g., Bank Transfer, JazzCash, EasyPaisa)', max_length=50, null=True)),
                ('payment_screenshot', models.ImageField(blank=True, help_text='Screenshot of payment proof', null=True, upload_to='payment_screenshots/')),
                ('additional_details', models.TextField(blank=True, help_text='Any additional payment details', null=True)),
                ('commission_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Commission amount for the referrer', max_digits=10)),
                ('commission_paid', models.BooleanField(default=False, help_text='Whether commission has been paid to referrer')),
                ('confirmed', models.BooleanField(default=False, help_text='Manually confirmed after checking payment screenshot')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('referrer', models.ForeignKey(blank=True, help_text='User who referred this payment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referred_payments', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
                ('referral_code', models.ForeignKey(blank=True, help_text='Referral/coupon code used', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='home.referralcode')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='referralcode',
            index=models.Index(fields=['code'], name='home_referr_code_08d0bf_idx'),
        ),
        migrations.AddIndex(
            model_name='referralcode',
            index=models.Index(fields=['user', 'is_active'], name='home_referr_user_id_d19e38_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['user', 'created_at'], name='home_paymen_user_id_053161_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['confirmed'], name='home_paymen_confirm_eda3e7_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['referral_code'], name='home_paymen_referra_a28da5_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['referrer'], name='home_paymen_referre_4f14a0_idx'),
        ),
    ]
