# Generated by Django 5.2.3 on 2026-01-04 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_referralcode_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='referralcode',
            name='mobile_number',
            field=models.CharField(blank=True, help_text='Mobile number for commission payments', max_length=15, null=True),
        ),
    ]
